language: node_js

sudo: true

node_js: stable

cache:
  directories:
    - node_modules

before_install:
  - echo '' > .npmrc

install:
  - npm install -g hexo-cli
  - npm install

script:
  - hexo clean
  - hexo g

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $DEPLOY_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep-history: false
  target-branch: master
  local-dir: public
  on:
    branch: hexo
