language: node_js

sudo: true

node_js: stable

cache:
  directories:
    - node_modules

before_install:
  - echo '' > .npmrc

install:
  - npm install -g hexo
  - npm install -g hexo-cli
  - npm install

script:
  - hexo generate

after_success:
  - git config user.name "sam leung" 
  - git config user.email "sam5372@aliyun.com"
  - sed -i'' "s~git@github.com:yanqing6628780/yanqing6628780.github.io.git~https://${DEPLOY_TOKEN}@${GH_REF}~" _config.yml
  - hexo deploy

env:
  global:
    - GH_REF: github.com/yanqing6628780/yanqing6628780.github.io.git
